//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPlug.Ext.ASM.DEK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiPlug.Ext.ASM.DEK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Ext.ASM.DEK.Models.Apps.ProductFiles.ProductFile
        ///
        ///&lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///            &lt;div class=&quot;span2&quot;&gt;
        ///                &lt;a class=&quot;btn btn-black&quot; style=&quot;height:44px; width:35px&quot; href=&quot;/apps/asm-dek/dek-product-files/&quot;&gt;&lt;i class=&quot;icon-arrow-left icon-large&quot;&gt;&lt;/i&gt;&lt;p&gt;Back&lt;/p&gt;&lt;/a&gt;
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;span8&quot;&gt;
        ///                &lt;h3 style=&quot;text-align:center&quot;&gt;Product File&lt;/h3&gt;
        ///            &lt;/div&gt;
        ///            &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProductFile {
            get {
                return ResourceManager.GetString("ProductFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Ext.ASM.DEK.Models.Apps.ProductFiles.ProductFiles
        ///@{ 
        ///    int i = 0;
        ///}
        ///&lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///            &lt;div class=&quot;span2&quot;&gt;
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;span8&quot;&gt;
        ///                &lt;h3 style=&quot;text-align:center&quot;&gt;DEK Product Files&lt;/h3&gt;
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;span2&quot;&gt;
        ///            &lt;/div&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///            &lt;h4&gt;Se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProductFiles {
            get {
                return ResourceManager.GetString("ProductFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Ext.ASM.DEK.Models.Apps.Settings.ProductFiles
        ///
        ///&lt;form action=&quot;&quot; method=&quot;post&quot; accept-charset=&quot;utf-8&quot; enctype=&quot;application/x-www-form-urlencoded&quot;&gt;
        ///    &lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///        &lt;div class=&quot;row-fluid&quot;&gt;
        ///            &lt;div class=&quot;box&quot;&gt;
        ///                &lt;div class=&quot;span2&quot;&gt;
        ///                    &lt;a class=&quot;btn btn-black&quot; style=&quot;height:44px; width:35px&quot; href=&quot;extensions/asm-dek/&quot;&gt;&lt;i class=&quot;icon-arrow-left icon-large&quot;&gt;&lt;/i&gt;&lt;p&gt;Back&lt;/p&gt;&lt;/a&gt;
        ///                    &lt;button type=&quot;submit&quot; value= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProductFilesSettings {
            get {
                return ResourceManager.GetString("ProductFilesSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Ext.ASM.DEK.Models.Apps.Settings.Home
        ///@{
        ///
        ///}
        ///&lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///            &lt;div class=&quot;span12&quot;&gt;
        ///                &lt;h3 style=&quot;text-align:center&quot;&gt;ASM DEK Settings&lt;/h3&gt;
        ///            &lt;/div&gt;
        ///        &lt;/div&gt;
        ///    &lt;/div&gt;
        ///
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box non-collapsible&quot;&gt;
        ///            &lt;div class=&quot;span10&quot;&gt;
        ///                &lt;h4&gt;Applications&lt;/h4&gt;
        ///                &lt;ol&gt;
        ///                    &lt;li&gt;&lt;a href=&quot;/extens [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsHome {
            get {
                return ResourceManager.GetString("SettingsHome", resourceCulture);
            }
        }
    }
}
