//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPlug.Ext.ASM.DEK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiPlug.Ext.ASM.DEK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Ext.ASM.DEK.Models.Apps.ProductFiles.ProductFile
        ///
        ///&lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///            &lt;div class=&quot;span4&quot;&gt;
        ///                &lt;a href=&quot;/&quot;&gt;&lt;img alt=&quot;IFTTT Logo&quot; src=&quot;&quot;&gt;&lt;/a&gt;
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;span5&quot;&gt;
        ///                &lt;p style=&quot;font-size:22.75px; padding-top:10px;&quot;&gt;Product File&lt;/p&gt;
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;span1&quot;&gt;
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;span2&quot;&gt;
        ///            &lt;/div&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProductFile {
            get {
                return ResourceManager.GetString("ProductFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Ext.ASM.DEK.Models.Apps.ProductFiles.ProductFiles
        ///@{ 
        ///    int i = 0;
        ///}
        ///&lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///            &lt;div class=&quot;span4&quot;&gt;
        ///                &lt;a href=&quot;/&quot;&gt;&lt;img alt=&quot;IFTTT Logo&quot; src=&quot;&quot;&gt;&lt;/a&gt;
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;span5&quot;&gt;
        ///                &lt;p style=&quot;font-size:22.75px; padding-top:10px;&quot;&gt;Product File&lt;/p&gt;
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;span1&quot;&gt;
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;span2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProductFiles {
            get {
                return ResourceManager.GetString("ProductFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Ext.ASM.DEK.Models.Apps.Settings.ProductFiles
        ///@{
        ///
        ///}
        ///&lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///            &lt;div class=&quot;span4&quot;&gt;
        ///                &lt;a href=&quot;/&quot;&gt;&lt;img alt=&quot;IFTTT Logo&quot; src=&quot;&quot;&gt;&lt;/a&gt;
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;span5&quot;&gt;
        ///                &lt;p style=&quot;font-size:22.75px; padding-top:10px;&quot;&gt;Product File App&lt;/p&gt;
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;span1&quot;&gt;
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;span2&quot;&gt;
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProductFilesSettings {
            get {
                return ResourceManager.GetString("ProductFilesSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model MultiPlug.Ext.ASM.DEK.Models.Apps.Settings.Home
        ///@{
        ///    int i = 0;
        ///}
        ///&lt;section class=&quot;row-fluid&quot;&gt;
        ///
        ///    &lt;div class=&quot;row-fluid&quot;&gt;
        ///        &lt;div class=&quot;box&quot;&gt;
        ///            &lt;div class=&quot;span4&quot;&gt;
        ///                &lt;a href=&quot;/&quot;&gt;&lt;img alt=&quot;IFTTT Logo&quot; src=&quot;&quot;&gt;&lt;/a&gt;
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;span5&quot;&gt;
        ///                &lt;p style=&quot;font-size:22.75px; padding-top:10px;&quot;&gt;ASM DEK Settings&lt;/p&gt;
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;span1&quot;&gt;
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;span2&quot;&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsHome {
            get {
                return ResourceManager.GetString("SettingsHome", resourceCulture);
            }
        }
    }
}
